name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install Dependencies Locally
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Code to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "/home/ec2-user/app"

    - name: Restart Flask App on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo yum update -y
          sudo yum install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip3 install --user -r /home/ec2-user/app/requirements.txt
          cd /home/ec2-user/app
          pkill -f "gunicorn" || true
          nohup gunicorn --workers 3 --bind 0.0.0.0:5000 app:app > app.log 2>&1 &
          sleep 5
          disown
